typedef enum GAME_FONT_ID
{
	GAME_FONT_ID_ZX_RUS,
	GAME_FONT_ID_BOLD_RUS,
	GAME_FONT_ID_DOS_RUS,

	GAME_FONT_ID_ZX_RUS_BORDER,
	GAME_FONT_ID_BOLD_RUS_BORDER,
	GAME_FONT_ID_DOS_RUS_BORDER,

	GAME_FONT_ID_ZX_RUS_THIN,
	GAME_FONT_ID_ZX_RUS_THIN_BORDER,

	GAME_FONT_ID_MICROFONT,
	GAME_FONT_ID_MICROFONT_BORDER,

} GAME_FONT_ID;

typedef enum GAME_SOUND_ID
{
	GAME_SOUND_ID_CLICK,
	GAME_SOUND_ID_BIPBIP,
	GAME_SOUND_ID_BIUBIU,

	GAME_SOUND_ID_ENUM_COUNT,
} GAME_SOUND_ID;

typedef enum TXT_LANG_ID_ENUMS
{
	TXT_LANG_ID_EN,
	TXT_LANG_ID_RU,

	TXT_LANG_ID_ENUM_COUNT,
} TXT_LANG_ID_ENUMS;
