typedef enum TXT_ID_ENUMS
{
	TXT_ID_WELCOME,
	TXT_ID_CONTINUE,
	TXT_ID_ACCEPT,
	TXT_ID_CANCEL,
	TXT_ID_ENTER,

	TXT_ID_LOG_IN,
	TXT_ID_SIGN_UP,

	TXT_ID_USER_NAME,
	TXT_ID_PASSWORD,

	TXT_ID_PASSWORD_AGAIN,
	TXT_ID_EMAIL,

	TXT_ID_LOGIN,
	TXT_ID_REGISTER,

	TXT_ID_USER_NAME_RULES,
	TXT_ID_NO_USER_OR_PASSWORD,
	TXT_ID_INCORRECT_EMAIL,
	TXT_ID_USERNAME_TAKEN,

	TXT_ID_PASSWORD_RULES,

	TXT_ID_ENUM_COUNT,
} TXT_ID_ENUMS;
